### ISSUE TITLE
Plugin causing HOOBS crash when trying to make an IFTTT web hook request?

### ISSUE THREAD

**Issue by mattiacolombomc** [350d/homebridge-http-garage-doors#1]
The plug-in is probably causing an HOOBS crash when trying to make a GET request with attributes to an IFTTT JSON HTTP web hook.
Can you help me figure out what's going on? Thanks in advance.
<img width="648" alt="Safari -24 -07-2022 at 14 44 06@2x" src="https://user-images.githubusercontent.com/55593934/180647609-cea88454-dafb-42aa-af5a-b15f4c61ad2a.png">

**Comment by 350d** [comment]
Hello! Can you provide your request setup here (without private keys)?
Also, update to latest version and check Homebridge UI log for extra debug info.
I don't have HOOBS to check it but your log looks not the same as on HB UI unfortunately. There should be config details/full object dump for every request and response.

**Comment by mattiacolombomc** [comment]
Hi! Thank you for your precious help.
Apparently, the new version of the plugin isn't shown in HOOBS. 
Plus, this is my configuration.

I simply need to make a plain GET request when the garage door is open. I also tried to set it app via in-app Apple Home automations via Shortcuts, but I had no success (even though I am 100% sure that the trigger URL is working)

This is the setup:
![Safari -24 -07-2022 at 17 30 25@2x](https://user-images.githubusercontent.com/55593934/180654417-031107f0-074b-4bd7-be28-8999fe9f2c77.png)

This is the error with this first setup:
<img width="1771" alt="Safari -24 -07-2022 at 17 31 41@2x" src="https://user-images.githubusercontent.com/55593934/180654476-5198a799-6afe-4907-9af0-f28f3311fb40.png">

Then I added some random parameters (as I told you, I just need a plain GET request):
![Safari -24 -07-2022 at 17 34 03@2x](https://user-images.githubusercontent.com/55593934/180654592-80124eff-3eb8-48ad-9a61-8d23bd0870d2.png)

Apparently the plugin was finally able to make the request at this time, but there was some other kind of error:
<img width="1517" alt="Safari -24 -07-2022 at 17 43 43@2x" src="https://user-images.githubusercontent.com/55593934/180655160-d159e0b4-e953-461e-84e0-3cc779be5c67.png">

Could you help me? Thanks again!

**Comment by 350d** [comment]
I will check IFTTT web hook later today and report here.
But as I can see here - The request could not be satisfied
403 error is on the IFTTT side, not on plugin side, but I will check anyway.

**Comment by mattiacolombomc** [comment]
Thank you so much!

**Comment by mattiacolombomc** [comment]
The fact is that if I click on the link manually, the error won't be shown (and the public IP address is obviously the same...)
Maybe the 403 is due to the fact that I send random parameters?
What if you check the error that the plugin outputs when trying to send NO JSON params/attributes or even empty params/attributes?

**Comment by mattiacolombomc** [comment]
Ok, I think we are dealing with a request format error here.
I tried to mask the link via shortening it with bit.ly, and the result was the following:
<img width="529" alt="Safari -24 -07-2022 at 17 52 58@2x" src="https://user-images.githubusercontent.com/55593934/180655569-5d641a44-b073-452e-ad8c-64da13add991.png">

Maybe it was because I sent "random" JSON parameters when the link wasn't expecting any?

At this point I think that the fastest solution would be to implement the possibility to send GET requests without any type of JSON attribute, thing that resulted in [this error](https://user-images.githubusercontent.com/55593934/180654476-5198a799-6afe-4907-9af0-f28f3311fb40.png) as written above.

Thank you again for your kind help!

P.S: last but not least, I'll leave here the IFTTT documentation. 
https://help.ifttt.com/hc/en-us/articles/4405029291163-Parsing-JSON-body-with-filter-code

**Comment by 350d** [comment]
Try to update to latest version 0.0.8
GET request with no body will be send now. Make sure you have FORM request method selected.

**Comment by 350d** [comment]
Also, following docs - you need POST request where JSON data can be send in body.

**Comment by mattiacolombomc** [comment]
Thanks, I will check later today!  Have a nice week :)

**Comment by mattiacolombomc** [comment]
I don't think the update has been pushed to HOOBS though:

https://plugins.hoobs.org/plugin/homebridge-http-garage-doors

![Safari -25 -07-2022 at 10 16 13@2x](https://user-images.githubusercontent.com/55593934/180730973-7533fa0f-8cbd-4dc0-b90c-b00b50367965.png)

**Comment by 350d** [comment]
Simply use POST as IFTTT documented, I guess it will work fine. OR if you still want to use GET method for some reason - just add your params in URL as designed for GET requests.

**Comment by mattiacolombomc** [comment]
> Also, following docs - you need POST request where JSON data can be send in body.

My fault! thanks again for all the help!
